// import 'package:flutter/material.dart';
//
// import '../../mobile/presentation/book_session/models/session_type_model.dart';
// import '../../mobile/presentation/history/models/history_model.dart';
// import '../../mobile/presentation/home/models/recommended_mentor.dart';
// import '../../mobile/presentation/home/models/top_user.dart';
// import '../../mobile/presentation/search/models/mentor_model.dart';
//
// class AppData {
//   static final List<TopUser> topUsers = [
//     TopUser(
//       id: 1,
//       image: "assets/images/people_images/Joumana Johnson.png",
//       name: "Joumana Johnson",
//       track: "Mobile",
//       hours: "48 shared",
//     ),
//     TopUser(
//       id: 3,
//       image: "assets/images/people_images/Youstina Hazem.png",
//       name: "Youstina Hazem",
//       track: "Ui/Ux",
//       hours: "45 shared",
//     ),
//     TopUser(
//       id: 2,
//       image: "assets/images/people_images/Max Turner.png",
//       name: "Max Turner",
//       track: "Backend",
//       hours: "43 shared",
//     ),
//     TopUser(
//       id: 11,
//       image: "assets/images/people_images/Liyan Alex.png",
//       name: "Liyan Alex",
//       track: "Fronted",
//       hours: "40 shared",
//     ),
//   ];
//
//   // static List<NextSession> nextSessions = [
//   //   NextSession(
//   //       image: "assets/images/people_images/Lisa Wang.png",
//   //       name: "Lisa Wang",
//   //       dateTime: "Today, 2:00 PM",
//   //       duration: "1h",
//   //       startsIn: "Starts in 10m",
//   //       isMentor: false,
//   //       remainingMinutes: 50),
//   //   NextSession(
//   //       image: "assets/images/people_images/Liyan Alex.png",
//   //       name: "Liyan Alex",
//   //       dateTime: "Today, 6:00 PM",
//   //       duration: "30m",
//   //       startsIn: "Starts in 4h",
//   //       isMentor: true,
//   //       remainingMinutes: 50),
//   // ];
//
//   static List<RecommendedMentor> recommendedMentors = [
//     RecommendedMentor(
//       id: 12,
//       image: "assets/images/people_images/Maria Garcia.png",
//       name: "Maria Garcia",
//       stars: 4.9,
//       track: "Mobile",
//     ),
//     RecommendedMentor(
//       id: 13,
//       image: "assets/images/people_images/Alex Johnson.png",
//       name: "Alex Johnson",
//       stars: 4.8,
//       track: "Mobile",
//     ),
//     RecommendedMentor(
//       id: 14,
//       image: "assets/images/people_images/Marcus Johnson.png",
//       name: "Marcus Johnson",
//       stars: 4.7,
//       track: "Mobile",
//     ),
//   ];
//
//   static List<SessionTypeModel> sessionTypes = [
//     SessionTypeModel(
//       icon: Icons.chat_bubble_outline,
//       title: "Text Chat",
//       description: "Simple text-based conversation. Great for quick questions.",
//     ),
//     SessionTypeModel(
//       icon: Icons.videocam_outlined,
//       title: "Video Call",
//       description:
//           "Face-to-face conversation with screen sharing capabilities.",
//     ),
//   ];
//
//   // static List<NotificationModel> notificationCard = [
//   //   NotificationModel(
//   //       bgColor: Color(0xFFD6D6D6).withValues(alpha: 0.25),
//   //       borderColor: Color(0xFFD6D6D6),
//   //       tag: "Reminder",
//   //       tagColor: Colors.grey,
//   //       timeAgo: "10 min ago",
//   //       title: "Reminder: Your mentorship session starts in 30 minutes.",
//   //       mentorName: "Sarah Johnson",
//   //       sessionTime: "Nov 25 at 2:00 PM",
//   //       icon: Icons.notifications_none_outlined,
//   //       dateTime: ""),
//   //   NotificationModel(
//   //       bgColor: Colors.green.shade50,
//   //       borderColor: Colors.green.shade200,
//   //       tag: "Approved",
//   //       tagColor: Colors.green,
//   //       timeAgo: "2 hours ago",
//   //       title: "Your session has been Approved!",
//   //       mentorName: "Michael Chen",
//   //       sessionTime: "Nov 25 at 2:00 PM",
//   //       icon: Icons.check_circle_outline),
//   //   NotificationModel(
//   //       bgColor: Colors.blue.shade50,
//   //       borderColor: Colors.blue.shade200,
//   //       tag: "Past session",
//   //       tagColor: Colors.blue,
//   //       timeAgo: "5 hours ago",
//   //       title: "Rate your session with the mentor.",
//   //       mentorName: "Emily Rodriguez",
//   //       sessionTime: "",
//   //       icon: Icons.star_border),
//   //   NotificationModel(
//   //       bgColor: Colors.yellow.shade50,
//   //       borderColor: Colors.yellow.shade300,
//   //       tag: "Pending",
//   //       tagColor: Colors.orange,
//   //       timeAgo: "1 day ago",
//   //       title: "Your session request is pending approval.",
//   //       mentorName: "David Kumar",
//   //       sessionTime: "Nov 28 at 10:00 AM",
//   //       icon: Icons.access_time),
//   //   NotificationModel(
//   //       bgColor: Colors.red.shade50,
//   //       borderColor: Colors.red.shade300,
//   //       tag: "Rejected",
//   //       tagColor: Colors.red,
//   //       timeAgo: "2 day ago",
//   //       title: "Your session request was declined.\nReason: Schedule conflict.",
//   //       mentorName: "Sarah Johnson",
//   //       sessionTime: "",
//   //       icon: Icons.cancel_outlined),
//   // ];
//
//   static List<MentorModel> mentors = [
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Joumana Johnson.png",
//       name: "Joumana Johnson",
//       status: "Busy",
//       rate: 4.9,
//       hours: 200,
//       price: 35,
//       skills: ["React", "JavaScript", "Html", "+7 more"],
//       responseTime: "4 hours",
//       track: "Frontend",
//     ),
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Max Turner.png",
//       name: "Max Turner",
//       status: "Available",
//       rate: 4.5,
//       hours: 150,
//       price: 25,
//       skills: ["Dart", "Flutter", "IOS", "+3 more"],
//       responseTime: "2 hours",
//       track: "Mobile",
//     ),
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Youstina Hazem.png",
//       name: "Youstina Hazem",
//       status: "Busy",
//       rate: 4.4,
//       hours: 95,
//       price: 20,
//       skills: ["Figma", "Adobe XD", "UI/UX", "+7 more"],
//       responseTime: "3 hours",
//       track: "Ui/Ux",
//     ),
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Amir Zahir.png",
//       name: "Amir Zahir",
//       status: "Available",
//       rate: 4.0,
//       hours: 85,
//       price: 20,
//       skills: ["React", "JavaScript", "Html", "+7 more"],
//       responseTime: "1 hour",
//       track: "Frontend",
//     ),
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Sarah Ali.png",
//       name: "Sarah Ali",
//       status: "Available",
//       rate: 5.0,
//       hours: 300,
//       price: 40,
//       skills: ["Flutter", "Dart", "Firebase", "+5 more"],
//       responseTime: "30 minutes",
//       track: "Mobile",
//     ),
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Mohamed Salah.png",
//       name: "Mohamed Salah",
//       status: "Busy",
//       rate: 3.9,
//       hours: 120,
//       price: 18,
//       skills: ["Python", "Django", "AI", "+6 more"],
//       responseTime: "5 hours",
//       track: "Backend",
//     ),
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Lara Smith.png",
//       name: "Lara Smith",
//       status: "Available",
//       rate: 4.7,
//       hours: 250,
//       price: 32,
//       skills: ["Figma", "UX Research", "Wireframing", "+4 more"],
//       responseTime: "6 hours",
//       track: "Ui/Ux",
//     ),
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Hazem Tarek.png",
//       name: "Hazem Tarek",
//       status: "Available",
//       rate: 4.8,
//       hours: 210,
//       price: 28,
//       skills: ["Node.js", "Express", "MongoDB", "+3 more"],
//       responseTime: "1 hour",
//       track: "Backend",
//     ),
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Emma Jones.png",
//       name: "Emma Jones",
//       status: "Busy",
//       rate: 4.2,
//       hours: 140,
//       price: 22,
//       skills: ["React Native", "JavaScript", "APIs", "+7 more"],
//       responseTime: "3 hours",
//       track: "Mobile",
//     ),
//     MentorModel(
//       id: "1",
//       image: "assets/images/people_images/Youssef Samir.png",
//       name: "Youssef Samir",
//       status: "Available",
//       rate: 3.5,
//       hours: 60,
//       price: 15,
//       skills: ["HTML", "CSS", "Bootstrap", "+2 more"],
//       responseTime: "1 hour",
//       track: "Frontend",
//     ),
//   ];
//
//   // static List<Session> pendingList = [
//   //   Session(
//   //       id: "1",
//   //       image: "assets/images/people_images/Marcus Johnson.png",
//   //       name: "Marcus Johnson",
//   //       role: "Mentor",
//   //       type: "Video Call",
//   //       dateTime: DateTime.now(),
//   //       price: "25",
//   //       status: "PendingApproval",
//   //       timeAgo: ""),
//   //   Session(
//   //       id: "2",
//   //       image: "assets/images/people_images/Sarah Smith.png",
//   //       name: "Sarah Smith",
//   //       role: "Mentor",
//   //       type: "1:1 Session",
//   //       dateTime: DateTime.now().add(const Duration(days: 1)),
//   //       price: "30",
//   //       status: "PendingApproval",
//   //       timeAgo: ""),
//   //   Session(
//   //       id: "3",
//   //       image: "assets/images/people_images/Alex Brown.png",
//   //       name: "Alex Brown",
//   //       role: "Mentor",
//   //       type: "Video Call",
//   //       dateTime: DateTime.now().add(const Duration(days: 2)),
//   //       price: "20",
//   //       status: "PendingApproval",
//   //       timeAgo: ""),
//   // ];
//
//   // static List<Session> confirmedList = [
//   //   Session(
//   //       id: "1",
//   //       image: "assets/images/people_images/Joumana Johnson.png",
//   //       name: "Joumana Johnson",
//   //       role: "Mentor",
//   //       type: "Video Session",
//   //       dateTime: DateTime(2025, 1, 12, 10, 30),
//   //       price: "35",
//   //       status: "Confirmed",
//   //       timeAgo: ""),
//   //   Session(
//   //       id: "2",
//   //       image: "assets/images/people_images/Leo Wong.png",
//   //       name: "Leo Wong",
//   //       role: "Software Engineer",
//   //       type: "Video Call",
//   //       dateTime: DateTime(2025, 1, 12, 14, 00),
//   //       price: "40",
//   //       status: "Confirmed",
//   //       timeAgo: ""),
//   //   Session(
//   //       id: "3",
//   //       image: "assets/images/people_images/Marcus Johnson.png",
//   //       name: "Marcus Johnson",
//   //       role: "Student",
//   //       type: "1:1 Session",
//   //       dateTime: DateTime(2025, 1, 13, 11, 00),
//   //       price: "Free",
//   //       status: "Live Now",
//   //       timeAgo: ""),
//   //   Session(
//   //       id: "4",
//   //       image: "assets/images/people_images/Sarah Smith.png",
//   //       name: "Sarah Smith",
//   //       role: "UI/UX Designer",
//   //       type: "Video Session",
//   //       dateTime: DateTime(2025, 1, 13, 16, 30),
//   //       price: "Free",
//   //       status: "Live Now",
//   //       timeAgo: ""),
//   //   Session(
//   //       id: "5",
//   //       image: "assets/images/people_images/Ahmed Ibrahim.png",
//   //       name: "Ahmed Ibrahim",
//   //       role: "Mobile Developer",
//   //       type: "Video Call",
//   //       dateTime: DateTime(2025, 1, 14, 12, 00),
//   //       price: "28",
//   //       status: "Confirmed",
//   //       timeAgo: ""),
//   //   Session(
//   //       id: "6",
//   //       image: "assets/images/people_images/Mariam Nasser.png",
//   //       name: "Mariam Nasser",
//   //       role: "Data Scientist",
//   //       type: "1:1 Session",
//   //       dateTime: DateTime(2025, 1, 14, 18, 00),
//   //       price: "45",
//   //       status: "Confirmed",
//   //       timeAgo: ""),
//   // ];
//   //
//   // static List<Session> requestList = [
//   //   Session(
//   //       id: "1",
//   //       image: "assets/images/people_images/Alex Johnson.png",
//   //       name: "Alex Johnson",
//   //       role: "React Development",
//   //       type: "Video Session",
//   //       dateTime: DateTime(2025, 1, 10, 11, 00),
//   //       price: "Free",
//   //       status: "NewRequest",
//   //       timeAgo: "10 min ago"),
//   //   Session(
//   //       id: "2",
//   //       image: "assets/images/people_images/Moritz Garcia.png",
//   //       name: "Moritz Garcia",
//   //       role: "System Engineering",
//   //       type: "Video Call",
//   //       dateTime: DateTime(2025, 1, 10, 14, 30),
//   //       price: "Free",
//   //       status: "NewRequest",
//   //       timeAgo: "2 hours ago"),
//   //   Session(
//   //       id: "3",
//   //       image: "assets/images/people_images/Aya Ahmed.png",
//   //       name: "Aya Ahmed",
//   //       role: "UI/UX Design",
//   //       type: "1:1 Session",
//   //       dateTime: DateTime(2025, 1, 11, 16, 00),
//   //       price: "Free",
//   //       status: "NewRequest",
//   //       timeAgo: "5 hours ago"),
//   // ];
//   //
//   // static List<Session> allList = [
//   //   Session(
//   //       id: "1",
//   //       image: "assets/images/people_images/Leo Wong.png",
//   //       name: "Leo Wong",
//   //       role: "Software Engineer",
//   //       type: "Video Call",
//   //       dateTime: DateTime(2025, 1, 12, 14, 00),
//   //       price: "40",
//   //       status: "Confirmed",
//   //       timeAgo: ""),
//   //   Session(
//   //       id: "2",
//   //       image: "assets/images/people_images/Sarah Smith.png",
//   //       name: "Sarah Smith",
//   //       role: "Mentor",
//   //       type: "Video Session",
//   //       dateTime: DateTime.now().add(const Duration(days: 1)),
//   //       price: "30",
//   //       status: "PendingApproval",
//   //       timeAgo: ""),
//   //   Session(
//   //       id: "3",
//   //       image: "assets/images/people_images/Marcus Johnson.png",
//   //       name: "Marcus Johnson",
//   //       role: "Student",
//   //       type: "Video Session",
//   //       dateTime: DateTime(2025, 1, 13, 11, 00),
//   //       price: "Free",
//   //       status: "Live Now",
//   //       timeAgo: ""),
//   // ];
//
//   static List<HistoryModel> completedSessions = [
//     HistoryModel(
//       id: "1",
//       name: "Joumana Johnson",
//       role: "Web Developer",
//       date: "Oct 3, 2025",
//       time: "4:00 PM",
//       duration: "60 min",
//       status: "Finished",
//       rating: 5,
//       imageUrl: "assets/images/people_images/Joumana Johnson.png",
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Lisa Wang",
//       role: "UI/UX Developer",
//       date: "Sep 26, 2025",
//       time: "1:00 PM",
//       duration: "45 min",
//       status: "Finished",
//       rating: 4,
//       imageUrl: "assets/images/people_images/Lisa Wang.png",
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Marcus Johnson",
//       role: "Mobile Developer",
//       date: "Sep 15, 2025",
//       time: "5:30 PM",
//       duration: "90 min",
//       status: "Finished",
//       rating: 0,
//       imageUrl: "assets/images/people_images/Marcus Johnson.png",
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Mark Anthony",
//       role: "Backend Developer",
//       date: "Sep 15, 2025",
//       time: "5:30 PM",
//       duration: "90 min",
//       status: "Finished",
//       rating: 0,
//       imageUrl: "assets/images/people_images/Mark Anthony.jpg",
//     ),
//   ];
//
//   static List<HistoryModel> cancelledSessions = [
//     HistoryModel(
//       id: "1",
//       name: "Sarah Adams",
//       role: "Mobile Developer",
//       date: "Oct 1, 2025",
//       time: "3:00 PM",
//       duration: "60 min",
//       status: "Cancelled",
//       rating: 0,
//       imageUrl: "assets/images/people_images/Sarah Adams.jpg",
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Daniel Lee",
//       role: "Data Science",
//       date: "Sep 28, 2025",
//       time: "11:00 AM",
//       duration: "30 min",
//       status: "Cancelled",
//       rating: 0,
//       imageUrl: "assets/images/people_images/Daniel Lee.jpg",
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Mia Fernandez",
//       role: "Web Developer",
//       date: "Sep 20, 2025",
//       time: "6:00 PM",
//       duration: "45 min",
//       status: "Cancelled",
//       rating: 0,
//       imageUrl: "assets/images/people_images/Mia Fernandez.jpg",
//     ),
//   ];
//
//   static List<HistoryModel> issueSessions = [
//     HistoryModel(
//       id: "1",
//       name: "Alex Johnson",
//       role: "Flutter Developer",
//       date: "Oct 2, 2025",
//       time: "2:00 PM",
//       duration: "60 min",
//       status: "Rejected",
//       rating: 0,
//       errorMessage: "Schedule conflict",
//       imageUrl: "assets/images/people_images/Alex Johnson.png",
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Kevin Smith",
//       role: "AI Basics",
//       date: "Sep 30, 2025",
//       time: "5:00 PM",
//       duration: "60 min",
//       status: "Rejected",
//       rating: 0,
//       errorMessage: "User unavailable",
//       imageUrl: "assets/images/people_images/Kevin Smith.jpg",
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Emily Carter",
//       role: "Business Strategy",
//       date: "Sep 22, 2025",
//       time: "7:00 PM",
//       duration: "45 min",
//       status: "Rejected",
//       rating: 0,
//       errorMessage: "Technical issue",
//       imageUrl: "assets/images/people_images/Emily Carter.jpg",
//     ),
//   ];
//
//   static List<HistoryModel> receivedReviews = [
//     HistoryModel(
//       id: "1",
//       name: "Joumana Johnson",
//       role: "Web Developer",
//       date: "Oct 5, 2025",
//       time: "6:00 PM",
//       duration: "60 min",
//       status: "Review",
//       rating: 5,
//       imageUrl: "assets/images/people_images/Joumana Johnson.png",
//       reviewComment: "Great mentor! Very clear and helpful.",
//       isReviewReceived: true,
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Lisa Wang",
//       role: "UI/UX Developer",
//       date: "Sep 29, 2025",
//       time: "2:00 PM",
//       duration: "45 min",
//       status: "Review",
//       rating: 4,
//       imageUrl: "assets/images/people_images/Lisa Wang.png",
//       reviewComment: "Explained concepts very well.",
//       isReviewReceived: true,
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Marcus Johnson",
//       role: "Mobile Developer",
//       date: "Sep 15, 2025",
//       time: "5:30 PM",
//       duration: "90 min",
//       status: "Finished",
//       rating: 0,
//       imageUrl: "assets/images/people_images/Marcus Johnson.png",
//       isReviewReceived: false,
//     ),
//     HistoryModel(
//       id: "1",
//       name: "Sarah Adams",
//       role: "Mobile Developer",
//       date: "Oct 1, 2025",
//       time: "3:00 PM",
//       duration: "60 min",
//       status: "Cancelled",
//       rating: 0,
//       imageUrl: "assets/images/people_images/Sarah Adams.jpg",
//       isReviewReceived: false,
//     ),
//   ];
// }
