// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbw52ZHxQ7h-rvu0dR12tQ-OoSrFwFUoU',
    appId: '1:450132003254:ios:1659a96cafd0e18e7fd917',
    messagingSenderId: '450132003254',
    projectId: 'skill-swap-e1a3d',
    storageBucket: 'skill-swap-e1a3d.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbw52ZHxQ7h-rvu0dR12tQ-OoSrFwFUoU',
    appId: '1:450132003254:ios:1659a96cafd0e18e7fd917',
    messagingSenderId: '450132003254',
    projectId: 'skill-swap-e1a3d',
    storageBucket: 'skill-swap-e1a3d.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACzUonmIHb3ROv1t6ZNUAqkYY6zJG_dak',
    appId: '1:450132003254:web:713521d6c447fa5b7fd917',
    messagingSenderId: '450132003254',
    projectId: 'skill-swap-e1a3d',
    authDomain: 'skill-swap-e1a3d.firebaseapp.com',
    storageBucket: 'skill-swap-e1a3d.firebasestorage.app',
    measurementId: 'G-4Q4GF24NHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW555ItYCcgqhrr5yykce_It88xve92Ho',
    appId: '1:450132003254:android:0e71a57fcc1a25297fd917',
    messagingSenderId: '450132003254',
    projectId: 'skill-swap-e1a3d',
    storageBucket: 'skill-swap-e1a3d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACzUonmIHb3ROv1t6ZNUAqkYY6zJG_dak',
    appId: '1:450132003254:web:792a5db1f830c5987fd917',
    messagingSenderId: '450132003254',
    projectId: 'skill-swap-e1a3d',
    authDomain: 'skill-swap-e1a3d.firebaseapp.com',
    storageBucket: 'skill-swap-e1a3d.firebasestorage.app',
    measurementId: 'G-SZGH3CJ3ZE',
  );
}
